image: node:alpine
stages:
  - install
  - test
  - deploy-staging
  - deploy-production

install-app:
  stage: install
  script: 
    - cd front
    - npm install
  cache:
    paths: 
      - node_modules
    policy: push
unit-test:
  stage: test
  script: 
    - cd front
    - npm run test-unit
  cache: 
    paths:
      - node_modules
    policy: pull
functional-test:
  stage: test
  script: 
    - cd front
    - npm run test-functional
  cache: 
    paths:
      - node_modules
    policy: pull
deploy-staging:
  stage: deploy-staging
  script: 
    - echo 'deploy staging'
deploy-production:
  stage: deploy-production
  script: 
    - echo 'deploy production'