image: node:alpine
stages:
  - install
  - test
  - build
  - deploy-staging
  - deploy-production

install-app:
  stage: install
  script: 
    - cd front
    - npm install
  cache:
    paths: 
      - node_modules
    policy: push
unit-test:
  stage: test
  script: 
    - cd front
    - npm run test-unit
  cache: 
    paths:
      - node_modules
    policy: pull
functional-test:
  stage: test
  script: 
    - cd front
    - npm run test-functional
  cache: 
    paths:
      - node_modules
    policy: pull
build-job:
  stage: build
  script:
    - cd front
    - npm run build
  cache: 
    paths:
      - node_modules
    policy: pull
  artifacts:
    name: 'front-build'
    expire_in: 1 week
    paths:
      - front/build
deploy-staging:
  stage: deploy-staging
  script:
    - cd front
    - ls -la 
    - echo 'deploy staging'
deploy-production:
  stage: deploy-production
  script: 
    - cd front
    - ls -la
    - echo 'deploy production'